name: Lint and Test

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tox-dev/action-pre-commit-uv@v1

  test:
    needs: pre-commit

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          # x86
          - ubuntu-latest
          - windows-latest
          - macos-13
          # arm64
          - ubuntu-24.04-arm
          - macos-latest
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync --dev -p "${{ matrix.python-version }}"

      - name: Run tests
        run: |
          uv run pytest --cov=src/portable_ffmpeg --cov-report=term-missing --cov-fail-under=100 | tee test_output.txt
          TEST_EXIT_CODE=${PIPESTATUS[0]}
          echo "## Coverage Summary" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          grep -A 20 "coverage.*=" test_output.txt >> $GITHUB_STEP_SUMMARY || echo "No coverage data found" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          exit $TEST_EXIT_CODE
